### ISSUE TITLE
Fix compilation issue with latex

### ISSUE THREAD

**Issue by jscamac** [jscamac/Alpine_Shrub_Experiment#3]
@wolass tried to reproduce paper at a recent [reproducibility hacka-thon](https://github.com/annakrystalli/OpenConBerlin_ReproHack) in Berlin. Appears analysis and figures were reproduced but the pdf of the manuscript would not compile (see his [issue](https://github.com/annakrystalli/OpenConBerlin_ReproHack/issues/2)).

I was unable to reproduce the error on my laptop (macbook pro) or iMac - both running 
```
pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016)
kpathsea version 6.2.2
Copyright 2016 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.21; using libpng 1.6.21
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.04
```

I was however, able to reproduce the error when using TeX Live 2013

```
pdfTeX 3.1415926-2.5-1.40.14 (TeX Live 2013)
kpathsea version 6.1.1
Copyright 2013 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.1; using libpng 1.6.1
Compiled with zlib 1.2.7; using zlib 1.2.7
Compiled with xpdf version 3.03
```

The underlying problem appears to be associated with line numbers. An immediate fix is to remove  `lineno` from the first line of both manuscript and supplementary Rnw files.

For example in manuscript.Rnw change this:
`\documentclass[9pt,twocolumn,twoside, lineno]{gcb}`

to this

`\documentclass[9pt,twocolumn,twoside]{gcb}`

Other options include adding Tex Live 2015 + to system requirements... or better yet. Dockerize project.

**Comment by pvesk** [comment]
Wack-o!

**Comment by jscamac** [comment]
Reverted to using a docker container
