### ISSUE TITLE
add a little more information about computation to readme

### ISSUE THREAD

**Issue by jscamac** [jscamac/Alpine_Shrub_Experiment#4]
@wolass tried to reproduce paper at a recent [reproducibility hacka-thon](https://github.com/annakrystalli/OpenConBerlin_ReproHack) in Berlin. Appears analysis and figures were reproduced but the pdf of the manuscript would not compile (see his [issue](https://github.com/annakrystalli/OpenConBerlin_ReproHack/issues/2)).

He pointed out that the analysis was slow (too ages). This is largely because its running 11 stan (bayesian models). I can make this clearer within the Readme. Computation varies depending on system and specs. But tests generally are ~ 1 hour.

**Comment by wolass** [comment]
On my laptop using ubuntu i7 4200 U 8 GB RAM the computation alone took 1:25 h, rendering of the paper <10 secs.
